/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package forme;

import forme.emisija.JPPrikazEmisija;
import forme.emisija.JPUnosEmisije;
import forme.kki.KKIFrmGlavna;
import forme.zaduzenje.JPZaduzenje;
import forme.zaposlen.JPPrikazZaposlenih;
import forme.zaposlen.JPUnosZaposlenog;
import javax.swing.JPanel;

/**
 *
 * @author Bojan
 */
public class FrmGlavna extends javax.swing.JFrame {
    
    JPanel aktivniPanel;

    /**
     * Creates new form FrmGlavna
     */
    public FrmGlavna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmRadSaZaposlenima = new javax.swing.JMenu();
        jmiUnosZaposlenog = new javax.swing.JMenuItem();
        jmiPrikazZaposlenih = new javax.swing.JMenuItem();
        jmRadSaZaduzenjima = new javax.swing.JMenu();
        jmiUnosZaduzenja = new javax.swing.JMenuItem();
        jmiPrikazZaduzenja = new javax.swing.JMenuItem();
        jmRadSaEmisijama = new javax.swing.JMenu();
        jmiUnosEmisije = new javax.swing.JMenuItem();
        jmiPrikazEmisija = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Snimanje emisija");
        setPreferredSize(new java.awt.Dimension(750, 660));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jmRadSaZaposlenima.setText("Rad sa zaposlenima");

        jmiUnosZaposlenog.setText("Unos zaposlenog");
        jmiUnosZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosZaposlenogActionPerformed(evt);
            }
        });
        jmRadSaZaposlenima.add(jmiUnosZaposlenog);

        jmiPrikazZaposlenih.setText("Prikaz zaposlenih");
        jmiPrikazZaposlenih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikazZaposlenihActionPerformed(evt);
            }
        });
        jmRadSaZaposlenima.add(jmiPrikazZaposlenih);

        jMenuBar1.add(jmRadSaZaposlenima);

        jmRadSaZaduzenjima.setText("Rad sa zaduzenjima");

        jmiUnosZaduzenja.setText("Unos zaduzenja");
        jmiUnosZaduzenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosZaduzenjaActionPerformed(evt);
            }
        });
        jmRadSaZaduzenjima.add(jmiUnosZaduzenja);

        jmiPrikazZaduzenja.setText("Prikaz zaduzenja");
        jmiPrikazZaduzenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikazZaduzenjaActionPerformed(evt);
            }
        });
        jmRadSaZaduzenjima.add(jmiPrikazZaduzenja);

        jMenuBar1.add(jmRadSaZaduzenjima);

        jmRadSaEmisijama.setText("Rad sa emisijama");

        jmiUnosEmisije.setText("Unos emisije");
        jmiUnosEmisije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosEmisijeActionPerformed(evt);
            }
        });
        jmRadSaEmisijama.add(jmiUnosEmisije);

        jmiPrikazEmisija.setText("Prikaz emisija");
        jmiPrikazEmisija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikazEmisijaActionPerformed(evt);
            }
        });
        jmRadSaEmisijama.add(jmiPrikazEmisija);

        jMenuBar1.add(jmRadSaEmisijama);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiUnosZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosZaposlenogActionPerformed
        JPUnosZaposlenog jpuz = new JPUnosZaposlenog();
        jpuz.setVisible(true);
        postaviAktivniPanel(jpuz);

    }//GEN-LAST:event_jmiUnosZaposlenogActionPerformed

    private void jmiPrikazZaposlenihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikazZaposlenihActionPerformed
        JPPrikazZaposlenih jppz = new JPPrikazZaposlenih(this);
        jppz.setVisible(true);
        postaviAktivniPanel(jppz);
    }//GEN-LAST:event_jmiPrikazZaposlenihActionPerformed

    private void jmiPrikazZaduzenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikazZaduzenjaActionPerformed
        JPZaduzenje jpz = new JPZaduzenje(false);
        jpz.setVisible(true);
        postaviAktivniPanel(jpz);
    }//GEN-LAST:event_jmiPrikazZaduzenjaActionPerformed

    private void jmiUnosZaduzenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosZaduzenjaActionPerformed
        JPZaduzenje jpz = new JPZaduzenje(true);
        jpz.setVisible(true);
        postaviAktivniPanel(jpz);
    }//GEN-LAST:event_jmiUnosZaduzenjaActionPerformed

    private void jmiUnosEmisijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosEmisijeActionPerformed
        JPUnosEmisije jpe = new JPUnosEmisije();
        jpe.setVisible(true);
        postaviAktivniPanel(jpe);
    }//GEN-LAST:event_jmiUnosEmisijeActionPerformed

    private void jmiPrikazEmisijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikazEmisijaActionPerformed
        JPPrikazEmisija jpe = new JPPrikazEmisija();
        jpe.setVisible(true);
        postaviAktivniPanel(jpe);
    }//GEN-LAST:event_jmiPrikazEmisijaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        KKIFrmGlavna.zatvoriProzor();
    }//GEN-LAST:event_formWindowClosing

    public void izmeniUnosZaposlenog(){
        JPUnosZaposlenog jpuz = new JPUnosZaposlenog();
        jpuz.setVisible(true);
        jpuz.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalji o zaposlenom"));
        postaviAktivniPanel(jpuz);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGlavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmRadSaEmisijama;
    private javax.swing.JMenu jmRadSaZaduzenjima;
    private javax.swing.JMenu jmRadSaZaposlenima;
    private javax.swing.JMenuItem jmiPrikazEmisija;
    private javax.swing.JMenuItem jmiPrikazZaduzenja;
    private javax.swing.JMenuItem jmiPrikazZaposlenih;
    private javax.swing.JMenuItem jmiUnosEmisije;
    private javax.swing.JMenuItem jmiUnosZaduzenja;
    private javax.swing.JMenuItem jmiUnosZaposlenog;
    // End of variables declaration//GEN-END:variables

    private void postaviAktivniPanel(JPanel noviPanel) {
        if (aktivniPanel!=null){
            getContentPane().remove(aktivniPanel);
        }
        
        getContentPane().add(noviPanel);
        aktivniPanel = noviPanel;

        this.revalidate();       
        this.repaint();
    }
    
}
