/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package forme.zaduzenje;

import domen.Zaduzenje;
import forme.zaduzenje.kki.KKIJPZaduzenje;

/**
 *
 * @author Bojan
 */
public class JPZaduzenje extends javax.swing.JPanel {
    private Zaduzenje selektovanoZaduzenje;

    /**
     * Creates new form JPZaduzenje
     */
    public JPZaduzenje(boolean unos) {
        initComponents();
        srediFormu();
        ucitajZaposlene();
        napuniTabeluPrikazZaduzenja();
        napuniTabeluUnosZaduzenja();
        ispisiUlogovanogPlanera();
        ucitajOpremu();
        selektovanoZaduzenje = new Zaduzenje();
        jpUnos.setVisible(unos);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrbgPretragaZaduzenja = new javax.swing.ButtonGroup();
        jrbSvaZaduzenja = new javax.swing.JRadioButton();
        jrbTrenutnaZaduzenja = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblZaduzenja = new javax.swing.JTable();
        jbtnKreirajZaduzenja = new javax.swing.JButton();
        jbtnDetalji = new javax.swing.JButton();
        jpUnos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfZaduzenjeID = new javax.swing.JTextField();
        jtfDatumZaduzenja = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlbPlanerUnos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblUnosZaduzenja = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jbtnDodaj = new javax.swing.JButton();
        jbtnSacuvaj = new javax.swing.JButton();
        jbtnObrisi = new javax.swing.JButton();
        jpDetalji = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jlbZaduzenjeID = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlbOprema = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlbEmisija = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlbDatumZaduzenja = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlbPlanerZaduzio = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtfDatumRazduzenja = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jlbPlanerRazduzio = new javax.swing.JLabel();
        jbtnRazduzi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jcbZaposleni = new javax.swing.JComboBox();

        jrbgPretragaZaduzenja.add(jrbSvaZaduzenja);
        jrbSvaZaduzenja.setText("Sva zaduzenja");
        jrbSvaZaduzenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSvaZaduzenjaActionPerformed(evt);
            }
        });

        jrbgPretragaZaduzenja.add(jrbTrenutnaZaduzenja);
        jrbTrenutnaZaduzenja.setText("Trenutna zaduzenja");
        jrbTrenutnaZaduzenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTrenutnaZaduzenjaActionPerformed(evt);
            }
        });

        jtblZaduzenja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblZaduzenja);

        jbtnKreirajZaduzenja.setText("Kreiraj zaduzenja");
        jbtnKreirajZaduzenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKreirajZaduzenjaActionPerformed(evt);
            }
        });

        jbtnDetalji.setText("Detalji");
        jbtnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetaljiActionPerformed(evt);
            }
        });

        jpUnos.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos zaduzenja"));

        jLabel1.setText("Zaduzenje ID:");

        jLabel2.setText("Datum zaduzenja:");

        jLabel3.setText("Zaduzio:");

        jlbPlanerUnos.setText("planer");

        jtblUnosZaduzenja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtblUnosZaduzenja);

        jLabel4.setText("Nova zaduzenja:");

        jbtnDodaj.setText("Dodaj");
        jbtnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajActionPerformed(evt);
            }
        });

        jbtnSacuvaj.setText("Sacuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jbtnObrisi.setText("Obrisi");
        jbtnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpUnosLayout = new javax.swing.GroupLayout(jpUnos);
        jpUnos.setLayout(jpUnosLayout);
        jpUnosLayout.setHorizontalGroup(
            jpUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpUnosLayout.createSequentialGroup()
                        .addComponent(jtfZaduzenjeID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(jpUnosLayout.createSequentialGroup()
                        .addGroup(jpUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDatumZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbPlanerUnos))
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jpUnosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        jpUnosLayout.setVerticalGroup(
            jpUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUnosLayout.createSequentialGroup()
                .addGroup(jpUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfZaduzenjeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpUnosLayout.createSequentialGroup()
                        .addGroup(jpUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfDatumZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jlbPlanerUnos)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpUnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDodaj)
                    .addComponent(jbtnObrisi)
                    .addComponent(jbtnSacuvaj))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpDetalji.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalji o zaduzenju"));

        jLabel6.setText("ZaduzenjeID:");

        jlbZaduzenjeID.setText("id");

        jLabel8.setText("Oprema:");

        jlbOprema.setText("naziv");

        jLabel10.setText("Emisija");

        jlbEmisija.setText("naziv");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Zaduzenje");

        jLabel7.setText("Datum:");

        jlbDatumZaduzenja.setText("datum");

        jLabel9.setText("Zaduzio:");

        jlbPlanerZaduzio.setText("planer");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Razduzenje");

        jLabel13.setText("Datum:");

        jLabel14.setText("Razduzio:");

        jlbPlanerRazduzio.setText("planer");

        jbtnRazduzi.setText("Razduzi");
        jbtnRazduzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRazduziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpDetaljiLayout = new javax.swing.GroupLayout(jpDetalji);
        jpDetalji.setLayout(jpDetaljiLayout);
        jpDetaljiLayout.setHorizontalGroup(
            jpDetaljiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetaljiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDetaljiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addGroup(jpDetaljiLayout.createSequentialGroup()
                        .addGroup(jpDetaljiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jpDetaljiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDetaljiLayout.createSequentialGroup()
                                .addComponent(jlbPlanerRazduzio)
                                .addGap(166, 166, 166)
                                .addComponent(jbtnRazduzi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlbPlanerZaduzio)
                            .addComponent(jlbDatumZaduzenja)
                            .addComponent(jlbEmisija)
                            .addComponent(jlbOprema)
                            .addComponent(jlbZaduzenjeID)
                            .addComponent(jtfDatumRazduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpDetaljiLayout.setVerticalGroup(
            jpDetaljiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetaljiLayout.createSequentialGroup()
                .addGroup(jpDetaljiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jlbZaduzenjeID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDetaljiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jlbOprema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDetaljiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jlbEmisija))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDetaljiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jlbDatumZaduzenja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDetaljiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jlbPlanerZaduzio))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDetaljiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtfDatumRazduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDetaljiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jlbPlanerRazduzio)
                    .addComponent(jbtnRazduzi))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jLabel5.setText("Zaposlen:");

        jcbZaposleni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpUnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(jcbZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrbSvaZaduzenja)
                        .addGap(18, 18, 18)
                        .addComponent(jrbTrenutnaZaduzenja)
                        .addGap(54, 54, 54)
                        .addComponent(jbtnKreirajZaduzenja)
                        .addGap(35, 35, 35)
                        .addComponent(jbtnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addComponent(jpDetalji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbSvaZaduzenja)
                    .addComponent(jrbTrenutnaZaduzenja)
                    .addComponent(jbtnKreirajZaduzenja)
                    .addComponent(jbtnDetalji))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jpUnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnKreirajZaduzenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKreirajZaduzenjaActionPerformed
        KKIJPZaduzenje.kreirajZaduzenja(jpUnos, jpDetalji, jtfZaduzenjeID, jtfDatumZaduzenja, jtfDatumRazduzenja, jtblUnosZaduzenja, jcbZaposleni);
    }//GEN-LAST:event_jbtnKreirajZaduzenjaActionPerformed

    private void jbtnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetaljiActionPerformed
        selektovanoZaduzenje = KKIJPZaduzenje.detalji(jtblZaduzenja, jpUnos, jpDetalji, selektovanoZaduzenje, jlbZaduzenjeID, jlbOprema, jlbEmisija, jlbDatumZaduzenja, jlbPlanerZaduzio, jtfDatumRazduzenja);        
    }//GEN-LAST:event_jbtnDetaljiActionPerformed

    private void jbtnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajActionPerformed
        KKIJPZaduzenje.dodaj(jtblUnosZaduzenja, jtfZaduzenjeID, jtfDatumZaduzenja, jcbZaposleni);
    }//GEN-LAST:event_jbtnDodajActionPerformed

    private void jbtnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiActionPerformed
        KKIJPZaduzenje.obrisi(jtblUnosZaduzenja);
    }//GEN-LAST:event_jbtnObrisiActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        KKIJPZaduzenje.sacuvaj(jtblUnosZaduzenja, jpUnos);
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jrbSvaZaduzenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSvaZaduzenjaActionPerformed
        KKIJPZaduzenje.svaZaduzenja(jcbZaposleni, jtblZaduzenja); 
    }//GEN-LAST:event_jrbSvaZaduzenjaActionPerformed

    private void jbtnRazduziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRazduziActionPerformed
        KKIJPZaduzenje.razduzi(selektovanoZaduzenje, jtfDatumRazduzenja, jpDetalji);
    }//GEN-LAST:event_jbtnRazduziActionPerformed

    private void jrbTrenutnaZaduzenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTrenutnaZaduzenjaActionPerformed
        KKIJPZaduzenje.trenutnaZaduzenja(jcbZaposleni, jtblZaduzenja);
    }//GEN-LAST:event_jrbTrenutnaZaduzenjaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnDetalji;
    private javax.swing.JButton jbtnDodaj;
    private javax.swing.JButton jbtnKreirajZaduzenja;
    private javax.swing.JButton jbtnObrisi;
    private javax.swing.JButton jbtnRazduzi;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JComboBox jcbZaposleni;
    private javax.swing.JLabel jlbDatumZaduzenja;
    private javax.swing.JLabel jlbEmisija;
    private javax.swing.JLabel jlbOprema;
    private javax.swing.JLabel jlbPlanerRazduzio;
    private javax.swing.JLabel jlbPlanerUnos;
    private javax.swing.JLabel jlbPlanerZaduzio;
    private javax.swing.JLabel jlbZaduzenjeID;
    private javax.swing.JPanel jpDetalji;
    private javax.swing.JPanel jpUnos;
    private javax.swing.JRadioButton jrbSvaZaduzenja;
    private javax.swing.JRadioButton jrbTrenutnaZaduzenja;
    private javax.swing.ButtonGroup jrbgPretragaZaduzenja;
    private javax.swing.JTable jtblUnosZaduzenja;
    private javax.swing.JTable jtblZaduzenja;
    private javax.swing.JTextField jtfDatumRazduzenja;
    private javax.swing.JTextField jtfDatumZaduzenja;
    private javax.swing.JTextField jtfZaduzenjeID;
    // End of variables declaration//GEN-END:variables

    private void ucitajZaposlene() {
        KKIJPZaduzenje.ucitajZaposlene(jcbZaposleni);
    }

    private void napuniTabeluPrikazZaduzenja() {
        KKIJPZaduzenje.napuniTabeluPrikazZaduzenja(jtblZaduzenja);
    }
    
    private void napuniTabeluUnosZaduzenja() {
        KKIJPZaduzenje.napuniTabeluUnosZaduzenja(jtblUnosZaduzenja, jcbZaposleni);
    }

    private void ispisiUlogovanogPlanera() {
        KKIJPZaduzenje.ispisiUlogovanogPlanera(jlbPlanerUnos, jlbPlanerRazduzio);
    }

    private void ucitajOpremu() {
        KKIJPZaduzenje.ucitajOpremu(jtblUnosZaduzenja);
    }
    
    private void ucitajEmisije() {
        KKIJPZaduzenje.ucitajEmisije(jtblUnosZaduzenja);
    }

    private void srediFormu() {
        KKIJPZaduzenje.srediFormu(jpUnos, jpDetalji, jtfZaduzenjeID, jtfDatumZaduzenja);
    }

}
